kind: Service
apiVersion: v1
metadata:
  name: win2019-vs-dotnet-rdp
spec:
  externalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 3389
      targetPort: 3389
      nodePort: 30221    ## Could by dynamic or documented somewhere
  type: NodePort
  selector:
    kubevirt.io/domain: win2019-vs-dotnet
    vm.kubevirt.io/name: win2019-vs-dotnet
